Repository acm-ucr/aviatr-website, pull requests merged in 2024-11, with the labels that each got.

#79 Add favicon
  src/app/favicon.ico
  src/app/layout.tsx
Labels: Ready to review

#52 Abhinav sharma/reccuring logo
  src/app/about/page.tsx
  src/app/events/page.tsx
  src/components/RecurringLogo.tsx
Labels: do not merge

#84 homepage push
  package-lock.json
  package.json
  src/images/home/homepagecover.webp
  src/layouts/NavBar.tsx
Labels: Ready to review

#85 Complete title compoent
  src/components/CenteredLineTitle.tsx
  src/components/ShiftedLineTitle.tsx
  src/components/about/BoardMemberSection.tsx
  src/components/about/WhatWeDo.tsx
  src/components/about/WhoWeAre.tsx
  src/components/events/UpcomingEvent.tsx
  src/components/home/MissionStatement.tsx
Labels: Ready to review

#97 Member detail
  public/about/Line_20.webp
  src/app/about/page.tsx
  src/components/MemberDetail.tsx
  src/components/about/BoardMemberSection.tsx
  src/data/boardMemberList.ts
Labels: help wanted

#132 add animation to hummingbird component
  src/components/projects/HummingBird.tsx
Labels: Ready to review

#135 Thomas/eagleanimate
  package-lock.json
  package.json
  src/components/projects/Eagle.tsx
Labels: Ready to review
