Repository acm-ucr/aviatr-website, pull requests merged in 2024-10, with the labels that each got.

#21 About Aviat
  package-lock.json
  package.json
  public/Arrow-1.webp
  src/app/page.tsx
  src/components/AboutAviat.tsx
Labels: Ready to review

#26 Created footer
  package-lock.json
  package.json
  public/footer/uas-logo-purple-ring.webp
  src/app/layout.tsx
  src/components/Footer.tsx
  tailwind.config.ts
Labels: Ready to review

#25 navbar start
  public/Images/Arrow-1.webp
  public/Images/Logo.webp
  src/app/layout.tsx
  src/components/NavBar.tsx
Labels: Ready to review, do not merge

#32 add "not found" component
  public/assets/notFound/drone.svg
  src/app/not-found.tsx
  src/components/NotFound.tsx
Labels: Ready to review

#33 Create board member component
  src/app/about/page.tsx
  src/components/about/BoardMember.tsx
  src/components/about/BoardMemberSection.tsx
  src/components/about/images/BMSLeftBorder.png
  src/components/about/images/BMSRightBorder.png
  src/components/about/images/defaultBoardMemberImage.jpeg
Labels: do not merge

#58 edit navbar to match figma
  public/Images/Logo.webp
  src/components/NavBar.tsx
Labels: Ready to review

#55 Created Hummingbird Homepage component
  public/homePage/hummingbird-image-1.webp
  public/homePage/hummingbird-image-2.webp
  public/homePage/hummingbird-image-3.webp
  src/app/page.tsx
  src/components/HummingbirdHomepage.tsx
Labels: Ready to review

#53 Edited footer component
  package-lock.json
  package.json
  public/footer/uas-logo-purple-ring.webp
  src/components/Footer.tsx
  tailwind.config.ts
Labels: Ready to review

#67 Hummingbird and Eagel in project
  package-lock.json
  package.json
  public/Images/Logo.webp
  public/about/BMSLeftBorder.webp
  public/about/BMSRightBorder.webp
  public/about/defaultBoardMemberImage.webp
  public/home/hummingbird-image-1.webp
  public/home/hummingbird-image-2.webp
  public/home/hummingbird-image-3.webp
  public/projects/Eagle1.webp
  public/projects/Eagle2.webp
  public/projects/Eagle3.webp
  public/projects/HummingBird.webp
  src/app/layout.tsx
  src/app/page.tsx
  src/app/projects/page.tsx
  src/components/about/BoardMemberSection.tsx
  src/components/about/images/BMSLeftBorder.png
  src/components/about/images/BMSRightBorder.png
  src/components/about/images/defaultBoardMemberImage.jpeg
  src/components/home/AboutAviat.tsx
  src/components/home/Eagle.tsx
  src/components/home/HummingbirdHomepage.tsx
  src/components/projects/Eagle.tsx
  src/components/projects/HummingBird.tsx
Labels: Ready to review

#73 Who We Are and What We Do component
  src/app/about/page.tsx
  src/components/about/WhatWeDo.tsx
  src/components/about/WhoWeAre.tsx
Labels: Ready to review

#74 Guru/puffin
  public/home/ProjectPuffin.webp
  src/app/page.tsx
  src/components/PuffinHomePageContent.tsx
Labels: Ready to review

#72 edit font and spacing
  src/components/not_found/NotFound.tsx
  src/images/notFound/drone.svg
  src/images/notFound/drone.webp
Labels: Ready to review

#77 Created Project Puffin Component in Projects page
  src/app/projects/page.tsx
  src/components/projects/ProjectPuffin.tsx
  src/images/projects/project-puffin-1.webp
  src/images/projects/project-puffin-2.webp
  src/images/projects/project-puffin-3.webp
Labels: Ready to review

#69 Created Upcoming Event Component
  src/app/events/page.tsx
  src/components/events/UpcomingEvent.tsx
  src/tailwindcss-extensions.d.ts
  tailwind.config.ts
Labels: Ready to review
